apiVersion: v1
kind: Namespace
metadata:
  name: veri
---
apiVersion: v1
kind: Service
metadata:
 name: veriservice
 namespace: veri
spec:
 selector:
   app: veri
 ports:
 - port: 10000
   targetPort: 10000
---
apiVersion: v1
kind: Service
metadata:
  name: veriservice-external
  namespace: veri
spec:
  selector:
    app: veri
  ports:
  - port: 5678
    targetPort: 10000
    name: "grpc"
  - port: 6060
    targetPort: 6060
    name: "pprof"
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: veri
  name: veri
  namespace: veri
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 1
  selector:
    matchLabels:
      app: veri
  template:
    metadata:
      labels:
        app: veri
    spec:
      containers:
        - name: veri
          image: berkgokden/veri:v0.0.100
          args: ["serve", "--services=veriservice:10000"]
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 10000
              name: "grpc"
              protocol: TCP
            - containerPort: 8000
              name: "http"
              protocol: TCP
            - containerPort: 6060
              name: "pprof"
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
            failureThreshold: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            failureThreshold: 3
            periodSeconds: 10
          startupProbe:
            httpGet:
              path: /ready
              port: http
            failureThreshold: 30
            periodSeconds: 10
          env:
            - name: BROADCAST
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: veri
  namespace: veri
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: veri
  minReplicas: 3
  maxReplicas: 15
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 900  # 15 minutes in seconds
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 20
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 20
