version: 2.1
jobs:
  build:
    docker:
      - image: cimg/go:1.20.4
    steps:
      - checkout
      - run: mkdir -p ./artifacts
      - run: ./test.sh
  publish-and-release:
    docker:
      - image: cimg/go:1.20.4
    steps:
      - checkout
      - add_ssh_keys
      - run: ./semver_version.sh -l go -f "./semver/version.go" -o none
      - run: sudo apt-get update && sudo apt-get install -y git bash curl build-essential
      - run: ./build.sh local
      - run: go get -u github.com/tcnksm/ghr
      - run: mkdir -p ./artifacts
      - run: cp ./bin/* ./artifacts
      - run: git config user.email "${GITHUB_EMAIL}"
      - run: git config user.name "${CIRCLE_PROJECT_USERNAME}"
      - run: ./semver_version.sh -l text -f ./artifacts/version.txt
      - run:
          name: "Publish Release on GitHub"
          command: |
            VERSION=$(cat ./artifacts/version.txt)
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./artifacts/
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: "Publish Release on Docker hub"
          command: |
            VERSION=$(cat ./artifacts/version.txt)
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker build -t berkgokden/veri:$VERSION .
            docker push berkgokden/veri:$VERSION
workflows:
  version: 2.1
  main:
    jobs:
      - build:
          filters:
            tags:
              only: /^(v)\d+\.\d+\.\d+$/
      - publish-and-release:
          requires:
            - build
          filters:
            branches:
              only:
                - master